### ISSUE TITLE
add item on header

### ISSUE THREAD

**Issue by elbertvaldian** [fengmu456/react-native-masonry-layout#1]
i know it is not a bug..

How can I add banner on the top at your mansory scroll view?
sorry, i am newbie at this.

thanks

**Comment by manyuanrong** [comment]
I added two properties to configure header and footer respectively, and update the document, because the work environment is not convenient, I did not do any test, you can try.

**Comment by elbertvaldian** [comment]
can you give me sample code for this?

sorry and thankyou

**Comment by manyuanrong** [comment]
```javascript
<Masonry
  ref="masonry"
  columns={3} // optional - Default: 2
  header={<View>
      <Text>Here is header</Text>
  </View>}
  renderItem={(item)=><View>
    <Text>some text</Text>
  </View>}
/>
```

**Comment by elbertvaldian** [comment]
halo,

i dont know why, but your code not working for me.
seems like header not functioning. :(

**Comment by elbertvaldian** [comment]
solved, i wrapeed the masonry and banner with ScrollView

thanks bro. your component is awesome!!!
