### ISSUE TITLE
how to perform onPress event on each item

### ISSUE THREAD

**Issue by kirtishjain9** [fengmu456/react-native-masonry-layout#5]
Hi Bro,

Thanks a lot for this amazing component. It really helps me a lot as I've implemented in my project.

Could you please tell me how do I perform onPress event or any select event on each masonary item (cell) to open a new detail view corresponding to that cell data.

Please help me out and give your views on this. I need it to implement urgently.

Thanks a lot in advance and waiting of your response.

Best regards
Kirtish Jain

**Comment by manyuanrong** [comment]
You can add any event binding in renderItem prop
```
<Masonry
  ref="masonry"
  columns={3} // optional - Default: 2
  renderItem={(item)=><View onClick={()=>{this.doSomething(item)}}>
    <Text>some text</Text>
  </View>}
/>
```
