### ISSUE TITLE
White screen after doing masonry.clear and masonry.addItems when all items is not fully rendered

### ISSUE THREAD

**Issue by fxbayuanggara** [fengmu456/react-native-masonry-layout#7]
I use this masonry to show my list of search. For my case, If I call a search function that will render 30 items, then I call search function again like:
```
{
res = getItem();
masonry.clear
masonry.addItems(res)
}
```

the screen then returns blank screen. 

It only worked if all items are rendered, otherwise, it returns a blank screen.

**Comment by AMINEDGE** [comment]
@fxbayuanggara I had a problem close to yours, for me I had this scenario

```javascript
masonry.clear()
masonry.addItemsWithHeight(items)
```

but the result was not clearing the items but appending new items to the old ones,
I fixed it by changing my function to async by adding the keyword when defining it and 
changed my code to this and it worked

```javascript
await masonry.clear()
await masonry.addItemsWithHeight(items)
```

**Comment by fxbayuanggara** [comment]
@AMINEDGE Yeay, thank you very much, it works beautifully!
